spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: "localhost"
      port: 27700
      database: "microservices"
      username: "msa"
      password: "examples"
