server:
  port: 8888
spring:
  application:
    name: "greetings"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: "localhost"
      port: 27700
      database: "microservices"
      username: "msa"
      password: "examples"
